# Generated by Django 5.1.4 on 2025-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField(blank=True, max_length=10000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
