# Generated by Django 5.1.4 on 2025-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='descr',
            field=models.TextField(blank=True),
        ),
    ]
