# Generated by Django 5.1.4 on 2025-01-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField(blank=True)),
                ('descr_man', models.TextField(blank=True)),
                ('descr_wom', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
