# Generated by Django 5.1.4 on 2025-01-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comm',
            old_name='descr',
            new_name='max_descr',
        ),
        migrations.RenameField(
            model_name='comm',
            old_name='descr_man',
            new_name='min_descr_man',
        ),
        migrations.RenameField(
            model_name='comm',
            old_name='descr_wom',
            new_name='min_descr_wom',
        ),
    ]
