# Generated by Django 5.1.4 on 2025-01-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='descr_man',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comm',
            name='descr_wom',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comm',
            name='descr',
            field=models.TextField(blank=True),
        ),
    ]
