# Generated by Django 5.1.4 on 2024-12-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Miss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True)),
                ('descr_1', models.TextField(blank=True, max_length=10000)),
                ('descr_2', models.TextField(blank=True, max_length=10000)),
            ],
        ),
    ]
