# Generated by Django 5.1.4 on 2025-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps_miss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_miss',
            name='descr_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comp_miss',
            name='descr_2',
            field=models.TextField(blank=True),
        ),
    ]
